<?php
/**
 * @author QuangChien(Glorious Victory) <quangchien01.it@gmail.com>
 * @copyright Copyright © 2022 QuangChien(Glorious Victory) <https://www.facebook.com/quangchien01>. All rights reserved.
 */
?>

<?php
/**
 * Author title view template
 *
 * @var $block \Victory\Blog\Block\Author\View
 */
?>
<div class="row">
    <div class="col l-8">
        <h1 class="page-title post-title">
            <?= $block->escapeHtml($block->getAuthorName()) ?>
        </h1>
    </div>
</div>
